
export const REQUEST_GAME_STATE_PENDING = 'REQUEST_GAME_STATE_PENDING';
export const REQUEST_GAME_STATE_SUCCESS = 'REQUEST_GAME_STATE_SUCCESS';
export const REQUEST_GAME_STATE_FAILED = 'REQUEST_GAME_STATE_FAILED';